app:
  port: 8080
  graceful_timeout: 1
  env: "test"
postgres:
  driver: postgres
  name: name
  user: user
  password: password
  host: localhost
  port: 5432
  ssl_mode: disable
  time_zone: UTC
table:
  user: user_infos

redis:
  url: redis:6379
  time_out: 30

token:
  access_token_duration: 30
  refresh_token_duration: 40
  private_key_path: keys/jwtRS256.key
  public_key_path: keys/jwtRS256.key.pub

oauth:
  google_issuer: "https://accounts.google.com"
  client_id: "----------------------"
  client_secret: "------------------"
  redirect_url: "http://localhost:8080/auth/api/v1/auth/sso/callback"

auth:
  allowed_roles:
    - admin
    -
sentry:
  dsn: <sentry-here>

migration:
  users:
    - username: sayfuddin
      email: sayf.uddin@pathao.com
      phone: 01763868877
      password: 12345678
      roles:
        - admin
    - username: fahimimam
      email: kazi.fahim@pathao.com
      phone: 01234567890
      password: 12345678
      roles:
        - invoice_creator
        - invoice_reader